### ISSUE TITLE
Funding

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#100]
Beside Jack Dorsey's 10 BTC bounty, which started all this, and the planned built-in zaps for repos, the project could apply for some longer term funding at some point:

OpenSats:
OpenSats is a public charity which aims to fund Bitcoin-related free and open source projects and associated education and research initiatives. We could apply [here](https://opensats.org/apply) at some point, but based on the projects listed I doubt we would be accepted before delivering something sustainable.

From the apply page:
"If your project is selected to be listed, we will reach out with any additional information necessary to ensure you are able to receive donation payouts. This may include tax related information depending on your location and/or bitcoin addresses in order to receive donation payouts from Open Sats."

Food for thought.

**Comment by PeerRich** [comment]
yeah lets apply after v.1.0

**Comment by PeerRich** [comment]
there is also https://nostrocket.org

**Comment by cypherhoodlum** [comment]
Just read it this morning! Good stuff. Actionable stuff.

**Comment by cypherhoodlum** [comment]
Hi @lucasnuic. This project is not ongoing anymore. I have joined the HORNETS team to get sovereign development on Nostr. We'll release Nestr alpha in May :rocket: In the meantime we can be sponsored [here](https://heya.fund/e/nevent1qqszh50wcpx3f4fazv64meldxu5usql084qzs3kwq2ew2u5nw6fdzqcppamhxue69uhkummnw3ezumt0d5pzpctjw0a66wrl2tsvsypdelydsvgw26hm3a9vfem98evv340c40cjwt9gvv)

**Comment by PeerRich** [comment]
@cypherhoodlum wanna return?

**Comment by cypherhoodlum** [comment]
I've been working with the HORNET Storage team for two years on a robust solution for git on Nostr so I'm gonna stick with that project 😁  we're very close.

**Comment by melvincarvalho** [comment]
@cypherhoodlum wish you luck.  I hope we can all collaborate in future.  I read more about HORNET and I see it has its own servers, which actually could be OK, if it doesnt stress the regular network.  There's also ngit.  So lets see how it all works out.  It's possible we can all have complementary solutions that work better together ...
