### ISSUE TITLE
Login with nsec

### ISSUE THREAD

**Issue by davidabram** [NostrGit/NostrGit#106]
### login with nsec

If I understand correctly, snort.social stores nsec in local storage.

Personally I don't want to store nsec in local storage or anywhere in the browser. It just expands attack surface and without security audit / experts in this domain I don't want to implement this feature.

I would rather drop this in favor of getalby or any browser extensions, even tho they store the nsec keys in the same manner.

_Originally posted by @davidabram in https://github.com/NostrGit/NostrGit/issues/20#issuecomment-1459137143_

**Comment by b35363** [comment]
That can be implemented,
It is very common to store the private key in the browser, even tho it's not optimal. We are kinda forced to use the browser.

We cannot expect every one to use Yubikey or Third-party software. But we can work around and implement nsec key encryption using a password / passphrase and storing it sharded. I'll check up for security issues if needed. 

https://github.com/NostrGit/NostrGit/discussions/92#discussion-4938097

**Comment by cypherhoodlum** [comment]
Closing as completed.
