### ISSUE TITLE
Can we force using rebase instead of merge ?

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#117]
<div type='discussions-op-text'>

<sup>Originally posted by **pierresisson** March  7, 2023</sup>
Hello there,

can we considerate using `rebase` instead of `merge` ?
context: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

i love using it because it keeps the history of `main` branch.
the githubs settings provide a params where when can choose to update branch with rebase
![image](https://user-images.githubusercontent.com/79455860/223554503-8b865d56-e761-418a-8029-7b3d02e4e405.png)

btw we can also use `squash and merge`, only pull request `commit` matters

What do you think?</div>

**Comment by pierresisson** [comment]
yeah i post it in discussion but if we choose to only use issue, it's better to be there !

**Comment by cypherhoodlum** [comment]
@pierresisson yeah, I converted each Discussion into Issue just now :+1:

**Comment by cypherhoodlum** [comment]
Sorry, but I'm not fully comfortable with this idea. :fearful: I feel the benefit of having somewhat cleaner commit history is nothing compared to the potential chaos rebasing can cause. It's a barrier of entry for casual contributors, I think. Not sure when it's safe to use myself.

**Comment by cypherhoodlum** [comment]
Even after reading the article. I'm a fan of squash and merge, which we are already doing.

**Comment by cypherhoodlum** [comment]
Closing as resolved by squashing commits when merging to main.
