### ISSUE TITLE
Should a repo be a normal npub?

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#118]
Do not use Discussion anymore, but:

### Discussed in https://github.com/NostrGit/NostrGit/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **PeerRich** March  5, 2023</sup>
i wonder if a repo should just be an npub key like a normal nostr user

we would get:

- nip5
- zap a repo
- follow a repo (star)
- description
- profile photo</div>

Let's continue the discussion here :heart:

**Comment by davidabram** [comment]
I am treating it as every repo has npub / nsec for the sake of https://github.com/NostrGit/NostrGit/issues/110

**Comment by cypherhoodlum** [comment]
Defining some words in the context of NostrGit:

Entity: A nostr profile (organisation / single account) which owns nostrgit repositories.
Repository: A nostr profile, which is directly linked to it's code / issues / PRs etc. Owned by an entity.

**Comment by cypherhoodlum** [comment]
Closing as duplicate with #115
