### ISSUE TITLE
Should we use localisation ?

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#123]
Do not use Discussions anymore, but:

### Discussed in https://github.com/NostrGit/NostrGit/discussions/81

<div type='discussions-op-text'>

<sup>Originally posted by **pierresisson** March  6, 2023</sup>
only english or should we use localisation ? 

https://en.wikipedia.org/wiki/Language_localisation

I prefer ask now because we need to implement it as soon as possible if we choose to localize</div>

Let's continue the discussion here :heart:

**Comment by pierresisson** [comment]
we conclude that we do not need localisation right now, 2 options :
- add label `later`
- close the issue

**Comment by cypherhoodlum** [comment]
Good points. There seems to be consensus that repos will be "normal npubs" as discussed in #118 and #110. The question about where code should be hosted can be found at #115. @melvincarvalho seems to be working on it actively. Let's continue the discussion in the relevant issue pages and close this issue completely as it's been established localisation is not important right now.

**Comment by comradekingu** [comment]
Adopting or leaving in the provisions to have translations for a brighter future seems to be a more pressing issue to decide on.
Hoping you use Weblate for when the time comes to do something about the outward-facing language support. :)
