### ISSUE TITLE
Error in GHA for eslint

### ISSUE THREAD

**Issue by e-roy** [NostrGit/NostrGit#128]
The check does pass, but there is an error in running eslint

![eslint error](https://user-images.githubusercontent.com/70700747/223794538-ef77651b-7a52-422f-a138-7f51640b4351.png)

This also causes a problem when running `yarn build` locally, and causing build to fail

**Comment by pierresisson** [comment]
thanks @e-roy will take a look

**Comment by pierresisson** [comment]
fixed
