### ISSUE TITLE
/signup dropdown should just be a normal button not a dropdown when logged out

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#138]
NIT: this should just be a normal button not a dropdown when logged out

![image](https://user-images.githubusercontent.com/8019099/224002867-bedcc72d-12c6-48c5-83f3-1d9a8ffc53f7.png)

_Originally posted by @PeerRich in https://github.com/NostrGit/NostrGit/issues/131#issuecomment-1461797693_

**Comment by pierresisson** [comment]
@PeerRich i fix something here, not sure if it was what you want ? https://github.com/NostrGit/NostrGit/pull/140
