### ISSUE TITLE
Change profile name into nav item in navbar (desktop & mobile view)

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#149]
Make profile name into a clickable link which leads to the profile page. This should be done both in desktop and mobile views (header.tsx and mobile-nav.tsx). Note that the profile page may have not been implemented yet.

![Screenshot from 2023-03-09 20-41-00](https://user-images.githubusercontent.com/82510823/224123799-75dfb5ff-5f58-4814-972c-a102b51e6a03.png)

**Comment by pierresisson** [comment]
taking this, (not have many time to this week so i take this little issue 👌🏻)
