### ISSUE TITLE
UI: Discussions

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#16]

**Comment by PeerRich** [comment]
yeah this would be the replicated.

i dont think you can easily port over existing UI since its written in Go but it shouldnt take me long to replicate the UI with tailwindcss

**Comment by PeerRich** [comment]
ui.shadcn.com runs on tailwind and radix-ui. its basically just a copy/pasteable set of pre-written components

**Comment by cypherhoodlum** [comment]
> So, just send a pull-request that you all accept? or is there any code review too ?
[Here](https://github.com/NostrGit/NostrGit/blob/main/documentation/development/contributing.md) are the relevant notes about contributing. Thanks for any contributions :)

**Comment by cypherhoodlum** [comment]
Not exactly sure in which step of the contribution workflow you're having problems with. I suggest reading [this](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) before anything else. Make sure to check the updated [contribution guidelines](https://github.com/NostrGit/NostrGit/blob/main/documentation/development/contributing.md) too. Yes, the code can be run on Windows 10.

**Comment by PeerRich** [comment]
lets focus on issues first. i never liked githubs discussions

**Comment by PeerRich** [comment]
since we are moving away from them too
