### ISSUE TITLE
Page for creating new nostrgit Issues

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#160]
/[entity]/[repo]/issues/new

I'll take on this feat. We want to push new events to the relays and subscribe to them. The structure of the events will form as I go.

**Comment by cypherhoodlum** [comment]
Pinging @e-roy so we won't do duplicate work.

**Comment by e-roy** [comment]
@cypherhoodlum #162 closes this correct?

**Comment by cypherhoodlum** [comment]
Correct.
