### ISSUE TITLE
Sign in and Sign up buttons are clickable only on the text.

### ISSUE THREAD

**Issue by cypherhoodlum** [NostrGit/NostrGit#163]
The whole buttons should be clickable, not just the text.

**Comment by kushalnl7** [comment]
Hi @cypherhoodlum, which buttons are you talking about? If they are the ones given in the below image, then they are working fine. Please confirm this.

<img width="252" alt="Screenshot 2023-03-12 at 1 33 22 PM" src="https://user-images.githubusercontent.com/64639902/224532200-e38379ed-7317-40e7-bd0d-4bc0a2b7f672.png">

**Comment by cypherhoodlum** [comment]
Yeah sorry, should have included a screenshot. Those are the correct buttons and it turns out the unresponsiveness of the buttons was caused by performance issues on my end. Buttons are working fine.

**Comment by kushalnl7** [comment]
> Yeah sorry, should have included a screenshot. Those are the correct buttons and it turns out the unresponsiveness of the buttons was caused by performance issues on my end. Buttons are working fine!

No problem @cypherhoodlum. Please mark my answer as the accepted one if possible. Thanks! 😊

**Comment by cypherhoodlum** [comment]
> Please mark my answer as the accepted one if possible. Thanks! blush

:smile: noted. But if you're refering to keeping track of contributions for the distribution of the possible bounty, we haven't created a proper system for keeping track yet. Stay tuned.

**Comment by kushalnl7** [comment]
Yes, I understand that. But, if you mark the answer as accepted, it will help me get a github badge for that.

**Comment by cypherhoodlum** [comment]
Oh okay, hold on, I'll figure out how to do that.

**Comment by kushalnl7** [comment]
> Oh okay, hold on, I'll figure out how to do that.
> 
> edit: I think that is only a feature in Discussions, sorry.

Got it. No problem!
