### ISSUE TITLE
use tailwindui if ui.shadcn.com doesnt have the component

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#167]
another thing to look into is https://tailwindui.com/

for example something like this: https://tailwindui.com/components/application-ui/forms/sign-in-forms

however don't use tailwindui components that require headlessui.com, it's an inferior version of radixui and we shouldn't mix both.

instead, try to rebuild the component using radix-ui.

**Comment by pierresisson** [comment]
agree!
