### ISSUE TITLE
user profile and entity page

### ISSUE THREAD

**Issue by e-roy** [NostrGit/NostrGit#172]
Is there any thought on how to structure for the user profile and the entity page(s)?

In github, the `[entity]` we currently have, would serve the profile of the user and the profile of the entity.  Would we take the same approach?  

If nostr handles identity around `npub`, would `npub` be used for tracking the entity?

**Comment by e-roy** [comment]
maybe this is connected to the thought in issue #161?

**Comment by cypherhoodlum** [comment]
Visually we can just follow the UI of a github profile for now. 
Let's continue the "under the hood" discussion in #161.

**Comment by PeerRich** [comment]
yeah visually it can be close to similar, under the hood discussion is more important

**Comment by e-roy** [comment]
closing this for discussion to be focused on #161
