### ISSUE TITLE
[NostrGit profile] auto post on twitter

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#176]
found this:

https://nostrwitter.onrender.com/

whatever you post on nostr will be posted on twitter 

we could try this

**Comment by PeerRich** [comment]
source https://github.com/ODevLibertario/nostrwitter

**Comment by cypherhoodlum** [comment]
Can you handle the twitter account? I don't want to touch it :smile:

**Comment by PeerRich** [comment]
sure! only need the nsec for the nostr account

**Comment by PeerRich** [comment]
@cypherhoodlum can you DM on nostr the nsec for the current account so I can test it?

**Comment by cypherhoodlum** [comment]
Sure :+1:

**Comment by PeerRich** [comment]
this tool is not what i was looking for

its not a sync, its its own interface that just posts to twitter and nostr
