### ISSUE TITLE
Clean up /issues and /pull pages mobile

### ISSUE THREAD

**Issue by e-roy** [NostrGit/NostrGit#177]
tighten up consistency for mobile on `/issues` and `/pull` pages

![issues-mobile](https://user-images.githubusercontent.com/70700747/224559195-ab6a5d36-c4f7-4ac1-a05b-20aec6af0175.png)
`/issues` page

![mobile-pulls](https://user-images.githubusercontent.com/70700747/224559245-57cc6305-ab4f-432b-b748-865f263f8c28.png)
`/pulls` page

**Comment by cypherhoodlum** [comment]
Sorry, I didn't notice you had assigned yourself already @e-roy. Removed the label.
The 'good first issue' and 'help wanted' are sometimes pretty similar labels.

**Comment by e-roy** [comment]
> Sorry, I didn't notice you had assigned yourself already @e-roy. Removed the label. The 'good first issue' and 'help wanted' are sometimes pretty similar labels.

no worries!  it was top of mind for me, I was feeling like I needed a casual low stress win 😄
