### ISSUE TITLE
Hydration errors

### ISSUE THREAD

**Issue by e-roy** [NostrGit/NostrGit#181]
Experiencing various hydration error when refreshing the page.  This happens when logged in using Alby.

![hydration-error1](https://user-images.githubusercontent.com/70700747/224570357-6f14ca1d-3084-4633-96ec-7afa6a7c1423.png)
![hydration-error2](https://user-images.githubusercontent.com/70700747/224570361-ec336593-b089-41f4-b786-4d5e90ea050a.png)
![hydration-error3](https://user-images.githubusercontent.com/70700747/224570365-4612d7ed-4ac0-4368-9581-43308474c1fa.png)

**Comment by e-roy** [comment]
@cypherhoodlum, I think these were the errors you were experiencing also

**Comment by cypherhoodlum** [comment]
Yes, looks familiar. I tracked the issue down to the header.tsx component. occurs when logged in. The rendering of profile details after the initial render causes all these problems. Fixed with a hook which returns null if initial render is not complete.

**Comment by e-roy** [comment]
> Yes, looks familiar. I tracked the issue down to the header.tsx component, occurs when logged in. The rendering of profile details after the initial component render causes all these problems. Fixed with a hook which returns null if initial render is not complete.

check out the solution in #181. Basically the same you did, but covering the entire app
