### ISSUE TITLE
add react-hook-forms

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#187]
> > before adding too much forms we should look into react-hook-form to make our lives easier
> 
> 
> 
> plus one for react-hook-form!

@e-roy wanna open a PR adding it?

_Originally posted by @PeerRich in https://github.com/NostrGit/NostrGit/pull/182#issuecomment-1465318971_

**Comment by e-roy** [comment]
> > > before adding too much forms we should look into react-hook-form to make our lives easier
> > 
> > 
> > plus one for react-hook-form!
> 
> @e-roy wanna open a PR adding it?
> 
> _Originally posted by @PeerRich in [#182 (comment)](https://github.com/NostrGit/NostrGit/pull/182#issuecomment-1465318971)_

Yeah, I can take this on 😃
