### ISSUE TITLE
nostr login

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#20]
lets replace this:
![CleanShot 2023-03-05 at 23 13 58@2x](https://user-images.githubusercontent.com/8019099/222988839-507feaec-1427-403a-a0f3-4be24c5c146c.jpg)

with a log in button that uses your nsec and then display your own avatar

![CleanShot 2023-03-05 at 23 14 21@2x](https://user-images.githubusercontent.com/8019099/222988848-9990501d-b8c7-4b57-8808-ed8bf692625b.jpg)

**Comment by cypherhoodlum** [comment]
Should include a warning about copying private key to the clipboard. Also nsec should never be fully visible in the login process.

**Comment by davidabram** [comment]
I am on it, I will make it to work with npub for time being, until we make a proper login process.

**Comment by PeerRich** [comment]
we should also add getalby.com support

**Comment by b35363** [comment]
> Should include a warning about copying private key to the clipboard. Also nsec should never be fully visible in the login process.

Very good idea, Clipboard are accessible clientside and can be retreived by a malicious middleman.

It's a quirky feature and hard to secure

https://webapps.stackexchange.com/questions/4076/the-dangers-of-web-apps-or-websites-maliciously-accessing-my-clipboard

I'll try to implement a secure private when I have the tile. too bad I'm flooded with work these days...

**Comment by davidabram** [comment]
I will split this issue.

**Comment by davidabram** [comment]
ATM https://github.com/NostrGit/NostrGit/pull/32 makes so you can login with pubkey and pubkey is stored in localstorage.

In the same pull request there is useSession which is a helper hook to see if you are logged in etc.

We need to support still nsec, nip-05, hex and alby login.

**Comment by davidabram** [comment]
### login with nsec

If I understand correctly, snort.social stores nsec in local storage.

Personally I don't want to store nsec in local storage or anywhere in the browser. It just expands attack surface and without security audit / experts in this domain I don't want to implement this feature.

I would rather drop this in favor of getalby or any browser extensions, even tho they store the nsec keys in the same manner.

**Comment by davidabram** [comment]
### login with nip-05

Really straight forward, you are getting npub with nip-05.

**Comment by davidabram** [comment]
###login with hex

If the hex is a pub key, store it the same way plain pub key is stored.

if the hex is a sec key see  https://github.com/NostrGit/NostrGit/issues/20#issuecomment-1459137143

**Comment by davidabram** [comment]
### login with getAlby

https://github.com/getAlby
