### ISSUE TITLE
Mobile: Update of Code Layout UI

### ISSUE THREAD

**Issue by gitstart** [NostrGit/NostrGit#211]
### Description

This ticket is to follow the design concepts of Github to implement some changes on the mobile version of the Code Layout page:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/26940294/225913087-6d43168f-8f19-468e-bd2a-3d71009ca7d8.png">

### Acceptance Criteria

-  This text should not be visible on smaller screens

![image](https://user-images.githubusercontent.com/26940294/225913683-99629730-90b3-4bf0-aaf8-501d320fad72.png)

- When the screen is made smaller, this text looks funny. It should be presented better (It could be truncated and the full text shown on hover)

![image](https://user-images.githubusercontent.com/26940294/225913853-04a21da1-fbbd-47fa-9794-e6999ba92338.png)

- These buttons should be either taken away or placed in a dropdown

![image](https://user-images.githubusercontent.com/26940294/225915839-3cecffbd-daac-4d8e-a41a-a740752bba0c.png)

> 1 and 2 should not show on mobile screens
> 3 ad 4 should be put in a dropdown on the right
> 5 should not show on mobile screens

The dropdown should look like this
![image](https://user-images.githubusercontent.com/26940294/225916044-17ac7496-767f-4e0f-ac70-6f9c7fee8f0a.png)

**Comment by gitstart** [comment]
We would like to work on this

**Comment by PeerRich** [comment]
assigned you!
