### ISSUE TITLE
store p2p data with orbit-db in NostrGit?

### ISSUE THREAD

**Issue by ghost** [NostrGit/NostrGit#221]
Hello, 

I would like to know what you all already thought about adding p2p data to the nostr with orbit-db. Have you all thought about adding p2p data to nostr with [orbit-db](https://github.com/orbitdb/orbit-db)?

**Comment by cypherhoodlum** [comment]
Hi, we have discussed IPFS previously and the rough consensus seems to be that we won't be using it in the NostrGit project for now. orbit-db uses IPFS and thus it won't work for us.

**Comment by marcelolucario** [comment]
Hi cypherhoodlum, thanks for feedback and information.
