### ISSUE TITLE
Business plans on NostrGit? 

### ISSUE THREAD

**Issue by ghost** [NostrGit/NostrGit#230]
Hello, an interesting idea would be for the community to provide an open core plan, part of the open code and support is paid, this to enable more features, developers, etc.

**Update:** I found an interesting discussion  about gitly business plans, thought it would be interesting if we could talk about that here with NostrGit.

*Concept*
- `https://about.nostrgit.com/pricing/`

Image

*idea?*
![image](https://user-images.githubusercontent.com/131043818/232606223-3cba7d22-0b10-499f-a856-355777353bcf.png)

reference: `https://github.com/vlang/gitly/issues/235`

**Comment by cypherhoodlum** [comment]
Hi, there are no plans to make any tiers or paid functionalities in NostrGit. The project will be completely free to use within the limitations of the related licenses. Future funding for the project is discussed [here](https://github.com/NostrGit/NostrGit/issues/100).
