### ISSUE TITLE
UI: Recent activity on NostrGit

### ISSUE THREAD

**Issue by ghost** [NostrGit/NostrGit#231]
Hello,

I would like to know what you all already thought about adding recent activity support to the NostrGit. Have you all thought about adding recent activity to NostrGit?

For example,

![image](https://user-images.githubusercontent.com/131187009/232851235-ff59b0d3-8f0e-4af4-8343-ec7c038a1eba.png)

what do you all think of this idea?

**Comment by cypherhoodlum** [comment]
Hi, yes this should be included in the landing page after login as discussed in #208. Closing this issue as duplicate.
