### ISSUE TITLE
turn tabs into pages

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#25]
right now these are tabs but they should be links to its pages

![CleanShot 2023-03-05 at 23 49 32@2x](https://user-images.githubusercontent.com/8019099/222990406-2b4798e1-2964-484d-a391-17309b3ba8e5.jpg)

**Comment by pierresisson** [comment]
and dropdown menu on mobile ?

**Comment by pierresisson** [comment]
can do this in https://github.com/NostrGit/NostrGit/pull/9

**Comment by PeerRich** [comment]
go for it! https://ui.shadcn.com/docs/primitives/dropdown-menu could be useful

**Comment by pierresisson** [comment]
done here https://github.com/NostrGit/NostrGit/pull/35
