### ISSUE TITLE
setup [dev] working branch, vs pushing to main

### ISSUE THREAD

**Issue by brycedev** [NostrGit/NostrGit#27]
i'm used to a workflow where we(devs) push PRed code to a default branch that's not production (main in this case) 

thoughts on adding an intermediary branch?

**Comment by PeerRich** [comment]
we should always open PRs, i just finished most of my work on `main` which happened when there were no other contributors

future code should always go via a PR (ideally an issue first and then via: "Create a branch" 

![CleanShot 2023-03-06 at 00 02 50@2x](https://user-images.githubusercontent.com/8019099/222990947-6d651ab6-5d0b-40cc-a878-955b84c3937f.jpg)

**Comment by PeerRich** [comment]
added branch protection to `main`
