### ISSUE TITLE
UI: Gist

### ISSUE THREAD

**Issue by ghost** [NostrGit/NostrGit#31]
Hi.

I wonder if it would be possible for NostrGit to have a Gist area for small snippets of source code. Would it be possible for NostrGit to have a gist area for small snippets of source code? For example, 

![image](https://user-images.githubusercontent.com/126974943/222996132-05ee4292-617a-43e1-9879-3f7ba53b8450.png)

?

**Comment by PeerRich** [comment]
of course!

**Comment by cypherhoodlum** [comment]
Closing this as a duplicate with #242.
