### ISSUE TITLE
Can we make function instead of arrow function in component naming ?

### ISSUE THREAD

**Issue by pierresisson** [NostrGit/NostrGit#34]
This :
`function Home() {}`
instead of this :
`const home = () => {}`

i think it is more readable and we can export function in one line ;) let me know!

**Comment by PeerRich** [comment]
agree

**Comment by cypherhoodlum** [comment]
+1

**Comment by cypherhoodlum** [comment]
Adding it to code conventions.

**Comment by pierresisson** [comment]
thx

**Comment by PeerRich** [comment]
reopening

**Comment by pierresisson** [comment]
did you fix this @PeerRich ?

**Comment by PeerRich** [comment]
not yet
