### ISSUE TITLE
Delete branche when pull request is merged 

### ISSUE THREAD

**Issue by pierresisson** [NostrGit/NostrGit#46]
what do you think about it ? you can set this on the settings tab

**Comment by PeerRich** [comment]
![CleanShot 2023-03-06 at 20 30 31@2x](https://user-images.githubusercontent.com/8019099/223211537-6f8f5fd2-7970-4a47-8f7b-f83318ec059f.jpg)

**Comment by pierresisson** [comment]
nice thx
