### ISSUE TITLE
Which github actions do we need ?

### ISSUE THREAD

**Issue by pierresisson** [NostrGit/NostrGit#55]
- prettier
- eslint
- nostrgit compliance (branche and pullrequest naming)

we do not have tests at the moment, maybe we can start a discussion about the stack

**Comment by PeerRich** [comment]
no tests needed yet, nothings working anyway yet 🤣

**Comment by pierresisson** [comment]
yes ik ahah, i was talking about a stack

**Comment by PeerRich** [comment]
playwright is decent

**Comment by pierresisson** [comment]
https://github.com/NostrGit/NostrGit/pull/60

**Comment by pierresisson** [comment]
closing this, eslint and prettier are on `main`
