### ISSUE TITLE
Make GHA required

### ISSUE THREAD

**Issue by pierresisson** [NostrGit/NostrGit#59]
![image](https://user-images.githubusercontent.com/79455860/223272047-ef1b46e4-0ce8-4c96-9c4c-fda817c8f6fa.png)
@PeerRich  https://github.com/NostrGit/NostrGit/pull/58

**Comment by pierresisson** [comment]
@PeerRich can you make Run / Prettier and Run / Eslint required pls ?
![image](https://user-images.githubusercontent.com/79455860/223416670-b91ae040-ce48-44ff-b6ef-76920fcd6cc7.png)

**Comment by PeerRich** [comment]
where do i do that?

**Comment by PeerRich** [comment]
done
