### ISSUE TITLE
vercel failed deploy insight

### ISSUE THREAD

**Issue by brycedev** [NostrGit/NostrGit#64]
@PeerRich is it possible to publicly surface the debug/error logs for Vercel when fails deploy? hard to understand sometimes why checks fail. i pushed a mishap to main somehow, earlier

**Comment by PeerRich** [comment]
not sure actually 

lemme investigate

**Comment by PeerRich** [comment]
but you can always run 

yarn build

locally

which is the same vercel is using

**Comment by PeerRich** [comment]
fixed. was a lint issue
