### ISSUE TITLE
mobile layout

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#7]
right now we're desktop only

**Comment by pierresisson** [comment]
We can check if tailwind's breakpoints are usable but we will have to make some adjustments I guess

**Comment by PeerRich** [comment]
oh yeah to clarify: I was referring to mobile layout

**Comment by pierresisson** [comment]
ok, working on it
can we have a mobile first approach ?
like this: `<div className="grid grid-cols-2 gap-6 lg:grid-cols-4">`

**Comment by PeerRich** [comment]
yeah `<div className="grid grid-cols-2 gap-6 lg:grid-cols-4">` looks good
