### ISSUE TITLE
Require screenshots or loom.com videos for PRs

### ISSUE THREAD

**Issue by PeerRich** [NostrGit/NostrGit#97]
we should ask for screenshots and loom videos for PRs

makes it faster to look into small things

**Comment by PeerRich** [comment]
especially because the vercel preview only runs if approved by a maintainer (or PR opened by a core member)

**Comment by cypherhoodlum** [comment]
It would make reviewing easier but would it also make the barrier of entry infeasible for casual contributors in the future? It's not the most approachable way of doing things, I think.

**Comment by PeerRich** [comment]
ok maybe not require but definitely mention a screenshot or video is helpful

**Comment by cypherhoodlum** [comment]
I can get behind that :+1:
